[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/.well-known/farcaster.json"
  to = "/api/farcaster"
  status = 200
  force = true

[[headers]]
  for = "/api/farcaster"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Cache-Control = "public, max-age=0, must-revalidate" 